version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped

  app_blue:
    image: "${BLUE_IMAGE}"
    container_name: app_blue
    environment:
      - PORT=${BLUE_PORT:-8081}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
    ports:
      - "${BLUE_PORT:-8081}:8081"

  app_green:
    image: "${GREEN_IMAGE}"
    container_name: app_green
    environment:
      - PORT=${GREEN_PORT:-8082}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
    ports:
      - "${GREEN_PORT:-8082}:8082"
